# General settings
seed: 42
use_cuda_if_available: true
tag: ""
model_filename: "lightgcn"

# Directory paths
data_dir: "../../data/"
output_dir: "./outputs/"

# Model configuration
hidden_dim: 64
n_layers: 3
alpha: null

# Training parameters
n_epochs: 150
lr: 0.01

# Model saving options
model_dir: "./models/"
model_name: "best_model.pt"