# Basic Configuration
seed: 42  # Seed for reproducibility
device: cpu  # Device to use: cpu or gpu

# Directories
data_dir: "../../data/"  # Directory for data
asset_dir: "asset/"  # Directory for assets
model_dir: "models/"  # Directory for storing models
output_dir: "outputs/"  # Directory for output files

# File Names
file_name: "full_train_data.csv"  # Name of the train file
test_file_name: "test_data.csv"  # Name of the test file
model_name: "best_model.pt"  # Name of the model file

# Data Process Parameters
split_ratio: 0.7
cv: 0
random_aug: False
stride: 0
sequence_split: False

# Training Parameters
num_workers: 2  # Number of workers
n_epochs: 300  # Number of training epochs
batch_size: 1024  # Batch size
lr: 0.0001  # Learning rate
clip_grad: 10  # Gradient clipping
patience: 30  # Patience for early stopping
log_steps: 50  # Logging frequency in steps
weight_decay: 0.01

# Loss Function
roc_star: True
gamma: 0.3

# Model Configuration
cate_cols: ["userID", "assessmentItemID"]
cont_cols: ["Timestamp"]
max_seq_len: 100  # Maximum sequence length
hidden_dim: 32  # Hidden dimension size
n_layers: 2  # Number of layers in the emodel
n_heads: 2  # Number of heads in the model
drop_out: 0.2  # Dropout rate

# Model, Optimizer, and Scheduler Types
model: lmf  # Type of model to use
optimizer: adam  # Type of optimizer
scheduler: plateau  # Type of learning rate scheduler
