# Basic Configuration
seed_fix: False
seed: 42  # Seed for reproducibility
device: gpu  # Device to use: cpu or gpu

# Directories
data_dir: "../../data/"  # Directory for data
asset_dir: "asset/"  # Directory for assets
model_dir: "models/"  # Directory for storing models
output_dir: "outputs/"  # Directory for output files

# File Names
file_name: "train_data.csv"  # Name of the train file
test_file_name: "test_data.csv"  # Name of the test file
model_name: "best_model.pt"  # Name of the model file

# Data Process Parameters
random_aug: False
session_aug: False
split_ratio: 0.8  # (train / (train+valid)) ratio
cv: 0  # for cross validation
stride: 0 # for sliding window
sequence_split: False

# Training Parameters
num_workers: 2  # Number of workers
n_epochs: 50  # Number of training epochs
batch_size: 512  # Batch size
lr: 0.00005  # Learning rate
weight_decay: 0.01
clip_grad: 10  # Gradient clipping
patience: 30  # Patience for early stopping
log_steps: 50  # Logging frequency in steps
weight_decay: 0.01

# Loss Function
roc_star: False
gamma: 0.3

# Model Configuration
cate_cols: ["userID", "testId", "assessmentItemID", "KnowledgeTag"]
cont_cols: ["Timestamp"]
defaults:
  - _self_
  - model : gcnlqtl #choose in [lstm, lstmattn, bert, lqtl, tl]

# Model, Optimizer, and Scheduler Types
optimizer: adamW  # Type of optimizer
scheduler: plateau  # Type of learning rate scheduler
loss_function: bce #bce, focal
focal_alpha: 0.7
focal_gamma: 4